version: "3.8"

services:
  todo-service:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    container_name: todo-service
    volumes:
      - ./docs:/root/docs
    environment:
      - USER_DB_HOST=host.docker.internal
      - USER_DB_PORT=3306
      - USER_DB_USERNAME=root
      - USER_DB_PASSWORD=
      - USER_DB_NAME=mst
      - TODO_DB_NAME=todo
      - APP_TOKEN=my-token
    ports:
      - "3000:3000"
    extra_hosts:
    - "host.docker.internal:host-gateway"